apiVersion: v1
kind: Secret
metadata:
  name: googletranslate-2api-secret
  labels:
    app.kubernetes.io/name: googletranslate-2api
type: Opaque
data:
  # base64("replace-me"); 生产不要提交真实值, 用 kubectl create secret 注入
  GOOGLE_API_KEY: "cmVwbGFjZS1tZQ=="
  API_MASTER_KEY: "cmVwbGFjZS1tZQ=="
